[book]
authors = ["Zoe Winters"]
language = "en"
multilingual = false
title = "Dusk Keyboard Layout"

# [preprocessor.toc]
# command = "mdbook-toc"
# renderer = ["html"]

[output.html]
site-url = "/dusk/"
default-theme = "Rust"
preferred-dark-theme = "Rust"
git-repository-url="https://github.com/luminespire/dusk/"
additional-css = ["theme/pagetoc.css"]
additional-js  = ["theme/pagetoc.js"]
